# Generated by Django 4.0.4 on 2022-05-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
