# Generated by Django 4.0.4 on 2022-05-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0003_film_desc_film_poster_film_rating_imdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, default='/media/posters/default.jpg', upload_to='posters'),
        ),
    ]
