# Generated by Django 4.0.4 on 2022-05-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0006_alter_film_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='desc',
            field=models.TextField(),
        ),
    ]
