# Generated by Django 4.0.4 on 2022-05-20 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0008_additionalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='additional_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='filmy.additionalinfo'),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(3, 'sci-fi'), (0, 'other'), (1, 'drama'), (2, 'comedy')], default=0),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='runtime',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
