# Generated by Django 4.0.4 on 2022-05-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0012_alter_additionalinfo_genre_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(0, 'other'), (3, 'sci-fi'), (1, 'drama'), (2, 'comedy')], default=0),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('films', models.ManyToManyField(to='filmy.film')),
            ],
        ),
    ]
