# Generated by Django 4.0.4 on 2022-05-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0014_alter_additionalinfo_genre_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='films',
            field=models.ManyToManyField(related_name='actors', to='filmy.film'),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(0, 'other'), (2, 'comedy'), (1, 'drama'), (3, 'sci-fi')], default=0),
        ),
    ]
